sudo: required

services:
- docker

language: rust

matrix:
  fast_finish: true
  include:
    - env: COLLECTD_VERSION=5.4 DEBIAN_VARIANT=collectd54 RELEASE=Y
    - env: COLLECTD_VERSION=5.5 DEBIAN_VARIANT=collectd55 RELEASE=Y
    - env: COLLECTD_VERSION=5.7 DEBIAN_VARIANT=collectd57 RELEASE=Y
    - env: UBUNTU_VERSION=14.04 COLLECTD_VERSION=5.4 RUST_TARGET=stable
    - env: UBUNTU_VERSION=16.04 COLLECTD_VERSION=5.5 RUST_TARGET=stable
    - env: UBUNTU_VERSION=18.04 COLLECTD_VERSION=5.7 RUST_TARGET=stable
    - env: UBUNTU_VERSION=19.10 COLLECTD_VERSION=5.7 RUST_TARGET=stable
    - env: UBUNTU_VERSION=18.04 COLLECTD_VERSION=5.7 RUST_TARGET=beta
    - env: UBUNTU_VERSION=18.04 COLLECTD_VERSION=5.7 RUST_TARGET=nightly

script:
  - bash ci/script.sh

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  api_key:
    secure: "t9UlGe33lcVJ3PjArcCQrXR7VRyUHnh3vp1I5EoZoz7uNcmTy6ZLHFPN7q9xMQ2c7QUgQPkVc2aU+uLe1GqY8yvtbqq0tOlGOm9TGSq5TCfYF8Aa7e92aIXFWcnXXWMNqO7pRK6CVFyd6zX8BF+IPBo79Tzg4OWtVMt9m5EkW3ZgDvZDreQPBE634yPpkY4YUSMXsI5hmaUrphEslCHMOaxbCdF73vbwVPNjeQGwEA5ya4VLTMlzHut6/tNAMx6nHkvdkNq9V3i8Fjle4H5vLmAyQwKViogfGjt2qABwQrOUyHBtcS0X03v4EIwF3c5zEFgIdyuX//z3FL6Z4+nDYB2pWbQxDhQOhtRctuDw4D7TfEQ6j6fvtiu9UGRjXULNWa2KG2Ip/z0+oO9Nz5E8nO2C3wjTT1X5c+ccG3/smHyM7TBEqHusLr0x3VapiRKK/N+WTeEprfiHhwvJJysUwXZktm8Hmt8sG2xr7fkt5nZ+EIMfb4kN7CPGIYLQFO/6wp/kMYnnxz+7wboVMZYrsGYPQpiTnT37+8e1G1f0AydykzP8ALZygx9A40jn8+qGCdyxyqj7qXdSfBvXPxn41jjy9JRtowxjAUStynkqnFpfBWuimd59xsbb768pT6zDSjkQCvQCOa2XdfVwTKdvf0/ubacNI4D9e/GihML8s68="

  file_glob: true
  file:
    - pg-collectd*.deb
  on:
    condition: $RELEASE = Y
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

