[package]
name = "pg-collectd"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]

[dependencies]
failure = "0.1.3"
log = "0.4.5"
serde = "1"
serde_derive = "1"
parking_lot = "0.6"
csv = "1"
collectd-plugin = "0.8.0"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.postgres]
version = "0.15"
features = ["with-chrono"]

[lib]
crate-type = ["cdylib"]
name = "pg_collectd"

[features]
bindgen = ["collectd-plugin/bindgen"]
