FROM ubuntu:18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    collectd \
    ca-certificates \
    build-essential \
    postgresql-client \
    curl \
 && rm -rf /var/lib/apt/lists/*
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
COPY . /tmp
WORKDIR /tmp
